OpenWebGAL/WebGAL_Terre

packages/origine2/src/pages/editor/EditorSidebar/SidebarTags/GameConfig/GameConfig.tsx
packages/terre2/src/Modules/manage-game/manage-game.service.ts

Configuration parsing optimization and deletion of old files before export

Fix: Configuration parse and export

---

package-lock.json
packages/origine2/src/pages/editor/GraphicalEditor/SentenceEditor/PixiPerform.tsx
packages/origine2/src/translations/en.ts
packages/origine2/src/translations/jp.ts
packages/origine2/src/translations/zh-cn.ts
yarn.lock

Added tanslation

---

packages/origine2/src/pages/editor/GraphicalEditor/SentenceEditor/Intro.tsx
packages/origine2/src/translations/en.ts
packages/origine2/src/translations/jp.ts
packages/origine2/src/translations/zh-cn.ts

*fontSize
*backgroundColor
*fontColor

add function

---

packages/origine2/src/pages/editor/GraphicalEditor/SentenceEditor/Say.tsx
packages/origine2/src/translations/en.ts
packages/origine2/src/translations/jp.ts
packages/origine2/src/translations/zh-cn.ts

TextBox_TextSize_Change

---

packages/origine2/src/pages/editor/GraphicalEditor/SentenceEditor/Intro.tsx
packages/origine2/src/translations/en.ts
packages/origine2/src/translations/jp.ts
packages/origine2/src/translations/zh-cn.ts

Details are listed below
https://github.com/MakinoharaShoko/WebGAL/issues/348

Added animation for Full Screen Text and added to delay time

---

packages/terre2/assets/templates/WebGAL_Template/game/animation/animationTable.json
packages/terre2/assets/templates/WebGAL_Template/game/animation/blur.json
packages/terre2/assets/templates/WebGAL_Template/game/animation/dotFilm.json
packages/terre2/assets/templates/WebGAL_Template/game/animation/glitchFilm.json
packages/terre2/assets/templates/WebGAL_Template/game/animation/godrayFilm.json
packages/terre2/assets/templates/WebGAL_Template/game/animation/oldFilm.json
packages/terre2/assets/templates/WebGAL_Template/game/animation/reflectionFilm.json
packages/terre2/assets/templates/WebGAL_Template/game/animation/removeFilm.json
packages/terre2/assets/templates/WebGAL_Template/game/animation/rgbFilm.json

Details here
https://github.com/MakinoharaShoko/WebGAL_Terre/issues/132

Add Json file for filter function

---

packages/origine2/src/pages/editor/GraphicalEditor/SentenceEditor/Bgm.tsx
packages/origine2/src/pages/editor/GraphicalEditor/SentenceEditor/ChangeBg.tsx
packages/origine2/src/translations/en.ts
packages/origine2/src/translations/jp.ts
packages/origine2/src/translations/zh-cn.ts

Click here for details
https://github.com/MakinoharaShoko/WebGAL/issues/341

unlock function add

---

packages/origine2/src/pages/editor/GraphicalEditor/SentenceEditor/ChangeBg.tsx
packages/origine2/src/pages/editor/GraphicalEditor/SentenceEditor/ChangeFigure.tsx
packages/origine2/src/pages/editor/GraphicalEditor/SentenceEditor/SetTransform.tsx
packages/origine2/src/translations/en.ts
packages/origine2/src/translations/jp.ts
packages/origine2/src/translations/zh-cn.ts

Reverts MakinoharaShoko/WebGAL_Terre#146

Revert "Fixed incomplete, inappropriate, and difficult translations"

---

packages/origine2/package.json
packages/origine2/src/config/info.ts
packages/origine2/src/hooks/useRelease.ts
packages/origine2/src/pages/dashboard/About.tsx
packages/origine2/src/pages/dashboard/DashBoard.tsx
packages/origine2/src/pages/dashboard/about.module.scss
packages/origine2/src/translations/en.ts
packages/origine2/src/translations/jp.ts
packages/origine2/src/translations/zh-cn.ts
packages/origine2/version-sync.js

Support for checking for updates

---

packages/origine2/src/pages/editor/EditorSidebar/SidebarTags/GameConfig/GameConfig.tsx
packages/origine2/src/pages/editor/EditorSidebar/SidebarTags/sidebarTags.module.scss
packages/origine2/src/translations/en.ts
packages/origine2/src/translations/jp.ts
packages/origine2/src/translations/zh-cn.ts

https://github.com/MakinoharaShoko/WebGAL_Terre/pull/80#issuecomment-1704057043

multiple arguments to display logo

---

packages/origine2/src/pages/dashboard/DashBoard.tsx
packages/origine2/src/pages/dashboard/GameElement.tsx
packages/origine2/src/pages/dashboard/GamePreview.tsx
packages/origine2/src/pages/dashboard/Sidebar.tsx
packages/origine2/src/pages/dashboard/dashboard.module.scss
packages/origine2/src/pages/dashboard/gameElement.module.scss
packages/origine2/src/pages/dashboard/gamepreview.module.scss
packages/origine2/src/pages/dashboard/sidebar.module.scss

Feat: game list new UI

---

packages/origine2/src/pages/editor/GraphicalEditor/SentenceEditor/PlayVideo.tsx
packages/origine2/src/translations/en.ts
packages/origine2/src/translations/jp.ts
packages/origine2/src/translations/zh-cn.ts

@MakinoharaShoko 
https://github.com/MakinoharaShoko/WebGAL/pull/386
Add relevant parameters

Added parameter to disable video skipping

---

packages/dev-server/index.js
packages/origine2/openapi.ts
packages/origine2/package.json
packages/origine2/vite.config.ts
packages/terre2/src/main.ts

Use environment variable `WEBGAL_PORT` to alter the listening port.
Pattern is the same, which means that both `WEBGAL_PORT` and `WEBGAL_PORT + 1` will be used.
Default is still 3000.

feat: listening port at env var WEBGAL_PORT

---

.github/workflows/build-terre.yml
.github/workflows/pr-check.yml
.github/workflows/release.yml
packages/WebGAL-electron/package.json
packages/WebGAL-electron/yarn.lock
yarn.lock

`navigator.keyboard` API is not work in the old version, need upgrade to the new version.

Update electron version

---

packages/origine2/src/components/Assets/Assets.tsx

Assets支持直接拖拽文件上传
Deal with issues : #203

Assets支持直接拖拽文件上传

---

packages/origine2/src/components/Assets/FileElement.tsx

在资源面板鼠标移动到文件名时显示缩略图（已支持的图片）
Deal with issues : #197

鼠标移动到文件名时显示缩略图

---

packages/origine2/src/pages/editor/MainArea/EditArea.tsx

修复打开无后缀文件报错

---

.github/workflows/build-terre.yml
.github/workflows/pr-check.yml
.github/workflows/release.yml

ref: 
- https://github.com/actions/download-artifact/compare/v2...v4
- https://github.com/actions/setup-node/compare/v3...v4

Update ci version

---

packages/origine2/src/api/Api.ts
packages/origine2/src/config/swagger.json
packages/origine2/src/pages/dashboard/DashBoard.tsx
packages/origine2/src/pages/dashboard/GameElement.tsx
packages/origine2/src/pages/dashboard/GamePreview.tsx
packages/origine2/src/pages/dashboard/Sidebar.tsx
packages/terre2/src/Modules/manage-game/manage-game.controller.ts
packages/terre2/src/Modules/manage-game/manage-game.dto.ts
packages/terre2/src/Modules/manage-game/manage-game.service.ts
packages/terre2/src/Modules/manage-template/manage-template.dto.ts

- Support for template config used by the game 
- Reduce HTTP requests

refactor: refactor game list api

---

packages/origine2/src/locales/en.po
packages/origine2/src/locales/ja.po
packages/origine2/src/locales/zhCn.po
packages/origine2/src/pages/editor/GraphicalEditor/SentenceEditor/ChangeFigure.tsx

添加了图形编辑器中的 Live2D Motion 和 Live2D Expression 选项的翻译

feat: localize Live2D options in SentenceEditor

---

packages/origine2/src/locales/en.po
packages/origine2/src/locales/ja.po
packages/origine2/src/locales/zhCn.po
packages/origine2/src/pages/templateEditor/TemplateEditor.tsx
packages/origine2/src/pages/templateEditor/TemplateEditorMainAria/TabsManager.tsx
packages/origine2/src/pages/templateEditor/TemplateEditorSidebar/ComponentTree/ComponentNode.tsx
packages/origine2/src/pages/templateEditor/TemplateEditorSidebar/ComponentTree/ComponentTree.tsx
packages/origine2/src/types/debugProtocol.ts
packages/origine2/src/utils/wsUtil.ts
packages/terre2/assets/templates/WebGAL_Template/game/scene/start.txt

feat: template editor edit sync action for issue#309

---

packages/origine2/src/locales/en.po
packages/origine2/src/locales/ja.po
packages/origine2/src/locales/zhCn.po
packages/origine2/src/pages/editor/GraphicalEditor/GraphicalEditor.tsx

recycle: `<GraphicalEditor>` component

---

packages/origine2/src/pages/editor/TextEditor/TextEditor.tsx

feat(text-editor): reload scene file on browser focus regain

---

packages/origine2/src/locales/en.po
packages/origine2/src/locales/ja.po
packages/origine2/src/locales/zhCn.po
packages/origine2/src/pages/editor/GraphicalEditor/components/EffectEditor.tsx

- 为倒角滤镜增添软化 (Softness) 选项
- 将倒角滤镜的 __强度__ 更改描述为 __透明度__, 因为我发现很多人被这个名称搞疑惑了

feat: add softness option for bevel filter

---

packages/origine2/src/locales/en.po
packages/origine2/src/locales/ja.po
packages/origine2/src/locales/zhCn.po
packages/origine2/src/pages/editor/Topbar/tabs/Export/ExportTab.tsx

feat: add export tip

---

packages/origine2/src/locales/en.po
packages/origine2/src/locales/ja.po
packages/origine2/src/locales/zhCn.po
packages/origine2/src/pages/editor/GraphicalEditor/SentenceEditor/ChangeBg.tsx
packages/origine2/src/pages/editor/GraphicalEditor/SentenceEditor/ChangeFigure.tsx
packages/origine2/src/pages/editor/GraphicalEditor/SentenceEditor/SetTransform.tsx
packages/origine2/src/pages/editor/GraphicalEditor/components/EffectEditor.tsx
packages/origine2/src/pages/editor/GraphicalEditor/utils/effectEditorConfig.ts
packages/origine2/src/pages/editor/GraphicalEditor/utils/rgbToColor.ts

- 重写组件`EffectEditor`，现在它的圈复杂度降低了
- 为`input`元素添加回车提交功能
- 将有关配置抽离成单独的文件
- 将关于色彩的工具函数抽离成单独的文件
- 不改变组件的外观、功能和用户使用方法
- 可以注意到组件仍有改进空间，例如输入合法性验证等，但本pr专注于实现一个功能和外观与原组件相同的组件，不打算添加更多新功能

refactor: effect editor
